# Generated by Django 5.1.5 on 2025-01-29 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('date', models.IntegerField()),
                ('dewey_decimal', models.CharField(blank=True, max_length=50)),
                ('dewey_wording', models.TextField(blank=True)),
                ('dimensions', models.CharField(blank=True, max_length=50)),
                ('entry_date', models.CharField(blank=True, max_length=10)),
                ('height', models.CharField(blank=True, max_length=50)),
                ('isbn', models.CharField(blank=True, max_length=50)),
                ('isbns', models.CharField(blank=True, max_length=50)),
                ('lc_classification', models.CharField(blank=True, max_length=50)),
                ('length', models.CharField(blank=True, max_length=50)),
                ('media', models.CharField(blank=True, max_length=50)),
                ('page_count', models.CharField(blank=True, max_length=50)),
                ('physical_description', models.CharField(blank=True, max_length=50)),
                ('primary_author', models.CharField(blank=True, max_length=200)),
                ('primary_author_role', models.CharField(blank=True, max_length=50)),
                ('publication', models.CharField(blank=True, max_length=500)),
                ('secondary_author', models.CharField(blank=True, max_length=200)),
                ('secondary_author_role', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('subjects', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('thickness', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('work_id', models.CharField(blank=True, max_length=50)),
                ('image_filename', models.CharField(default='image.jpg', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
    ]
