# Generated by Django 5.1.5 on 2025-01-24 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HappinessListItem',
        ),
        migrations.AlterField(
            model_name='wordoftheyear',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 24, 14, 53, 59, 398059, tzinfo=datetime.timezone.utc)),
        ),
    ]
