# Generated by Django 5.1.5 on 2025-01-26 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0002_delete_happinesslistitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordoftheyear',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 26, 22, 6, 54, 226054, tzinfo=datetime.timezone.utc)),
        ),
    ]
