# Generated by Django 5.1.5 on 2025-01-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0005_alter_wordoftheyear_created_at'),
    ]

    operations = [
    ]
