# Generated by Django 5.1.5 on 2025-01-28 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0006_auto_20250128_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordoftheyear',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
