# Generated by Django 5.1.5 on 2025-01-26 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='AlcoholEntry',
        ),
        migrations.AlterModelOptions(
            name='alcoholentry',
            options={'verbose_name_plural': 'Alcohol Entries'},
        ),
    ]
