# Generated by Django 5.1.5 on 2025-01-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0002_rename_entry_alcoholentry_alter_alcoholentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcoholentry',
            name='distiller_website',
            field=models.URLField(default='https://www.example.com'),
        ),
        migrations.AddField(
            model_name='alcoholentry',
            name='image_filename',
            field=models.CharField(default='image.jpg', max_length=200),
        ),
    ]
