# Generated by Django 5.1.5 on 2025-01-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0003_alcoholentry_distiller_website_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlcoholEntry',
            new_name='Beverage',
        ),
    ]
