# Generated by Django 5.1.5 on 2025-01-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0004_rename_alcoholentry_beverage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beverage',
            options={'verbose_name_plural': 'Beverages'},
        ),
    ]
