# Generated by Django 5.1.5 on 2025-01-26 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StitchingProjectEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('stitching_type', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 1, 26, 23, 52, 23, 157601, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stitching Projects',
            },
        ),
    ]
