# Generated by Django 5.1.5 on 2025-01-27 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stitching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stitchingprojectentry',
            name='image_filename',
            field=models.CharField(default='image.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='stitchingprojectentry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 0, 6, 15, 396663, tzinfo=datetime.timezone.utc)),
        ),
    ]
